name = "MoireHamiltonian"
uuid = "7384aa0e-b09a-45df-9bc5-b3dd6317c65f"
authors = ["Mao Yoshii <mao@g.ecc.u-tokyo.ac.jp>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Plots = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
